Issue17
RazvanKokovics/SimpleApi pull request #19
Opened 2020-04-10 06:29 UTC by RazvanKokovics

Closes #17. Should be merged after #16.

2020-04-10 06:32 UTC, gasher commented
Please use a better name for this PR

2020-04-10 12:38 UTC, gasher commented on service/expression.js
> +    expressionRepository.deleteExpressionFromUsers(expressionId);
I might be wrong but shouldn't you await this or return it to be awaited in the controller?

2020-04-10 12:41 UTC, gasher commented on service/users.js
>      userRepository.deleteUser(userName);
Here as well. I dont think you are await-ing it in the repository so the promise wont be await-ed at all

2020-04-10 12:41 UTC, gasher requested changes
I saw some issues that might be related to this PR

2020-04-13 13:23 UTC, gasher commented on service/expression.js
> +      throw new InexistentItem('ExpressionId does not exists.');
This message is quite confusing. I think you are talking about an expression with that id that doesn't exists.

2020-04-13 13:23 UTC, gasher commented on service/users.js
> +      throw new InexistentItem('Username does not exists.');
Same here, the user with that username doesn't exists

2020-04-14 11:39 UTC, RazvanKokovics commented
This PR was re-made in #25 .

2020-04-14 11:39 UTC, closed without merging